openapi: 3.0.0
info:
  title: Order API
  version: 1.0.0
servers:
  - url: http://localhost:8080
tags:
  - name: Order

paths:
  /v1/orders:
    post:
      summary: Create a new order
      tags:
        - Order
      operationId: createOrder
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OrderRequest'
      responses:
        '201':
          description: Order created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderResponse'

components:
  schemas:

    OrderRequest:
      type: object
      required:
        - items
      properties:
        items:
          type: array
          minItems: 1
          description: List of products to order
          items:
            type: object
            required:
              - productId
              - quantity
            properties:
              productId:
                type: string
                format: uuid
                description: Identifier for the product
              quantity:
                type: integer
                minimum: 1
                description: Quantity of the product

    OrderResponse:
      type: object
      required:
        - id
        - status
      properties:
        id:
          type: string
          format: uuid
          description: Order unique identifier
        status:
          type: string
          enum:
            - SUCCEEDED
            - FAILED
          description: Order status
        createdAt:
          type: string
          format: date-time
          description: Order creation date-time
          example: 2024-07-15T20:48:19.4020439
        totalPrice:
          type: string
          format: decimal
          description: Order total price
          example: 22.2
