openapi: 3.0.0
info:
  title: Product API
  version: 1.0.0
servers:
  - url: http://localhost:8080
tags:
  - name: Product

paths:
  /v1/products:search:
    post:
      summary: Search requested products
      tags:
        - Product
      operationId: searchProducts
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductSearchRequest'
      responses:
        '200':
          description: A list of products.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'

components:
  schemas:

    ProductSearchRequest:
      type: object
      required:
        - productIds
      properties:
        productIds:
          type: array
          items:
            type: string
            format: uuid

    Product:
      type: object
      required:
        - id
        - name
        - price
        - quantity
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        price:
          type: string
          format: decimal
        quantity:
          type: integer
          format: int32
